# Generated by Django 4.1.6 on 2023-06-26 13:55

import appEquipements.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=appEquipements.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAttribue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=1000)),
                ('nbColumn', models.IntegerField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Valeurr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribue', models.CharField(max_length=1000)),
                ('valeur', models.CharField(max_length=1000)),
                ('equipements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEquipements.equipements')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=1000)),
                ('id_Equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEquipements.equipements')),
            ],
        ),
        migrations.AddField(
            model_name='equipements',
            name='typeEquipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEquipements.typeequipe'),
        ),
        migrations.CreateModel(
            name='Attribue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1000)),
                ('typeAttribue', models.CharField(max_length=1000)),
                ('typeEquipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEquipements.typeequipe')),
            ],
        ),
    ]
