# Generated by Django 4.1.6 on 2023-06-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipements', '0002_tache_id_typeequipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='typeequipe',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEquipements.position'),
        ),
    ]
